fix #21 add dependency for xstream
This commit adds a fixed dependency for xstream version 1.4.8 because
the spring-boot dependency graph downgraded it to version 1.4.2 which
resulted in a NoClassDefFoundError.